/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PracticeAreasRouteImport } from './routes/practice-areas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FirmsIndexRouteImport } from './routes/firms.index'
import { Route as LawyersSlugRouteImport } from './routes/lawyers.$slug'
import { Route as FirmsSlugRouteImport } from './routes/firms.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminFirmsRouteImport } from './routes/_authenticated/admin.firms'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasRoute = PracticeAreasRouteImport.update({
  id: '/practice-areas',
  path: '/practice-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmsIndexRoute = FirmsIndexRouteImport.update({
  id: '/firms/',
  path: '/firms/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyersSlugRoute = LawyersSlugRouteImport.update({
  id: '/lawyers/$slug',
  path: '/lawyers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmsSlugRoute = FirmsSlugRouteImport.update({
  id: '/firms/$slug',
  path: '/firms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFirmsRoute = AuthenticatedAdminFirmsRouteImport.update({
  id: '/admin/firms',
  path: '/admin/firms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/firms/$slug': typeof FirmsSlugRoute
  '/lawyers/$slug': typeof LawyersSlugRoute
  '/firms/': typeof FirmsIndexRoute
  '/admin/firms': typeof AuthenticatedAdminFirmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/firms/$slug': typeof FirmsSlugRoute
  '/lawyers/$slug': typeof LawyersSlugRoute
  '/firms': typeof FirmsIndexRoute
  '/admin/firms': typeof AuthenticatedAdminFirmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/firms/$slug': typeof FirmsSlugRoute
  '/lawyers/$slug': typeof LawyersSlugRoute
  '/firms/': typeof FirmsIndexRoute
  '/_authenticated/admin/firms': typeof AuthenticatedAdminFirmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/practice-areas'
    | '/register'
    | '/search'
    | '/sitemap.xml'
    | '/dashboard'
    | '/firms/$slug'
    | '/lawyers/$slug'
    | '/firms/'
    | '/admin/firms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/practice-areas'
    | '/register'
    | '/search'
    | '/sitemap.xml'
    | '/dashboard'
    | '/firms/$slug'
    | '/lawyers/$slug'
    | '/firms'
    | '/admin/firms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/practice-areas'
    | '/register'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/firms/$slug'
    | '/lawyers/$slug'
    | '/firms/'
    | '/_authenticated/admin/firms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PracticeAreasRoute: typeof PracticeAreasRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FirmsSlugRoute: typeof FirmsSlugRoute
  LawyersSlugRoute: typeof LawyersSlugRoute
  FirmsIndexRoute: typeof FirmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas': {
      id: '/practice-areas'
      path: '/practice-areas'
      fullPath: '/practice-areas'
      preLoaderRoute: typeof PracticeAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firms/': {
      id: '/firms/'
      path: '/firms'
      fullPath: '/firms/'
      preLoaderRoute: typeof FirmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyers/$slug': {
      id: '/lawyers/$slug'
      path: '/lawyers/$slug'
      fullPath: '/lawyers/$slug'
      preLoaderRoute: typeof LawyersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firms/$slug': {
      id: '/firms/$slug'
      path: '/firms/$slug'
      fullPath: '/firms/$slug'
      preLoaderRoute: typeof FirmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/firms': {
      id: '/_authenticated/admin/firms'
      path: '/admin/firms'
      fullPath: '/admin/firms'
      preLoaderRoute: typeof AuthenticatedAdminFirmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminFirmsRoute: typeof AuthenticatedAdminFirmsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminFirmsRoute: AuthenticatedAdminFirmsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PracticeAreasRoute: PracticeAreasRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FirmsSlugRoute: FirmsSlugRoute,
  LawyersSlugRoute: LawyersSlugRoute,
  FirmsIndexRoute: FirmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
